wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1686169477.799429
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.10.6
      5: 0.15.3
      8:
      - 1
      - 5
